name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  greeting:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3]

    steps:
    - uses: actions/checkout@v2
    - name: hellow world
      run: echo Hello, world

      shell: bash

  goodbye:
    runs-on: ubuntu-latest
    needs: [greeting]
    steps:
    - name: Goodbye, world
      run: echo "Goodbye, world"

      shell: bash